language: generic

sudo: required # superuser level permissions for this build
services:
  - docker

before_install:
  - docker build -t bevdokimov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bevdokimov/docker-react npm run test

deploy:
# travis supports a couple of providers out of the box and can automatically deploy our app
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-414241562937"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

